version: '3'
services:
    db:
        image: dolthub/dolt-sql-server
        ports:
        - 3306
        volumes:
        - ./db/sql:/docker-entrypoint-initdb.d
    py-srv:
        build: py-srv
        ports:
        - 80:8000
